---
title: "Proyecto 8 EDA"
format: html
editor: visual
jupyter: python3
---

```{r}
library(reticulate)
py_config()
reticulate::py_install(c("numpy","pandas"))
```

Se tomará el archivo de Excel **MunicipiosSequia.xlsx** como base inicial para hacer la preparación y limpieza de los datos.

```{python}
import pandas as pd # Manejo de datos en tablas
import numpy as np # Operaciones numéricas
```

Suponiendo que la base se encuentra en los Files de R, importamos la información:

```{python}
df = pd.read_excel("MunicipiosSequia.xlsx")
# podemos ver más o menos como es la estructura de nuestra base
print(df.head(10))
print(df.shape)
print(df.columns)
```

Como tenemos un DataFrame municipio x fecha de la base de datos original, limpiaremos la base para tener la info en municipio-mes, listo para EDA y modelado.

```{python}
# las columnas que no son fechas
eda_cols = df.columns[:9]
print(eda_cols)
```

Del mapa oficial de categorías, podemos renombrar las intensidades de sequia:

```{python}
eda_intensidad = {np.nan: 0, 'D0': 1, 'D1': 2, 'D2': 3, 'D3': 4, 'D4': 5}
print(eda_intensidad)

eda_int_labels = {0: 'Sin sequía', 1: 'D0 Anormalmente seco', 2: 'D1 Sequía Moderada', 3: 'D2 Sequía Severa',
                  4: 'D3 Sequía Extrema', 5: 'D4 Sequía Excepcional'}
print(eda_int_labels)
```

Transformamos las columnas de fecha en filas:

```{python}
fecha_cols = [f for f in df.columns if f not in eda_cols]
print(fecha_cols)
print(f"{df.shape[0]} municipios, {len(fecha_cols)} columnas de fecha")
```

Considerando que tenemos informacion desde el mes de enero de 2003, hasta septiembre de 2026 que es hasta donde está actualizada la base, deberíamos tener 12 columnas por año de 2003 a 2025 y 9 columnas de 2026, i.e., 12×23+9=285, pero tenemos muchas más. Veamos porqué sucede esto.

```{python}
fechas_serie = pd.Series(fecha_cols)
print(fechas_serie)
```

Notemos que las fechas en un inicio son a final de mes, pero en las ultimas fechas tenemos dos fechas por mes, es decir, la información mostrada es quincenal, ya no mensual.

```{python}
conteo_anual = fechas_serie.dt.year.value_counts().sort_index()
print("Columnas de fecha por año: ")
print(conteo_anual)
```

Dada la siguiente información en la fuente de donde obtuvimos nuestros datos:\
*"El archivo en Excel® contiene los municipios afectados por alguna condición desde anormalmente seco (D0) hasta sequía excepcional (D4). Para el periodo 2003 a 2015 se asignó la categoría de sequedad o sequía (D0 a D4) cuando la categoría cubría al menos el 40% de la superficie de dicho municipio. Sin embargo, debido a retroalimentación recibida, a partir de 2016 se asigna la categoría de sequía a la de mayor intensidad observada en algún municipio."*, y que nuestra base cuenta con información de forma mensual en 2003-2013 (12 columnas/año) y de forma quincenal desde 2014 ( al rededor de 24 columnas/año); se decidió que para tener una base comparable en terminos de fechas y de registro de información, **recortaremos la base a ene-2016** para contar con registros consistentes quincenales en cada mes.

```{python}
cols_2016 = [c for c in fecha_cols if c.year >= 2016]
print(f"Número de periodos a partir de 2016:", len(cols_2016))
```

Creamos una copia de nuestro DataFrame original para poder hacer modificaciones necesarias.

```{python}
df_eda = df[list(eda_cols) + list(cols_2016)].copy()
print(df_eda.shape)
print(df_eda.columns)
```

Dejamos las variables de `eda_cols` como vienen en el DataFrame, pero vamos a pivotear las columnas de fecha con su clasificación de sequía, es decir, las columnas de fecha ahora serán filas y se crea la columna de `clasificacion_sequia` para cada fecha y municipio. El número de filas del nuevo DataFrame corresponde al número de periodos (285) por cada entidad federativa (32) para cada municipio dentro de ellas (depende de la entidad).

```{python}
df_clasif_municipio = df_eda.melt(id_vars=eda_cols, var_name='fecha', value_name='clasificacion_sequia')
df_clasif_municipio['fecha'] = pd.to_datetime(df_clasif_municipio['fecha'])
print(df_clasif_municipio)
```

Mapeamos las intensidades para "eliminar" los NaNs, ya que por la naturaleza de la base los NaN significan que no hay sequía.

```{python}
df_clasif_municipio['intensidad'] = df_clasif_municipio['clasificacion_sequia'].map(eda_intensidad) df_clasif_municipio['intensidad']
```

También creamos una columna con la descripción de este código numérico que utilizamos para clasificar la intensidad.

```{python}
df_clasif_municipio['intensidad_desc'] = df_clasif_municipio['intensidad'].map(eda_int_labels)
df_clasif_municipio['intensidad_desc']
```

Por el momento esta será la base a utilizar para el modelado y la ingeniería de variables: `df_clasif_municipio`