# -*- coding: utf-8 -*-
"""Proyecto_Modulo_8-EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/gapalfaro-cmyk/Proyecto-de-fin-de-modulo-8---Alfaro-Badillo-Cruz-Perez-Rupit/blob/main/Proyecto_Modulo_8-EDA.ipynb

Se tomará el archivo de Excel **MunicipiosSequia.xlsx** como base inicial para hacer la preparación y limpieza de los datos.
"""

import pandas as pd # Manejo de datos en tablas
import numpy as np # Operaciones numéricas
import matplotlib.pyplot as plt  # Gráficas
import seaborn as sns  # Gráficas más avanzadas

# Importamos la información
df = pd.read_excel("MunicipiosSequia.xlsx")
df.head(10)

df.shape

df.columns

"""Como tenemos un DataFrame municipio x fecha de la base de datos original: **Monitor de Sequía CONAGUA**, limpiaremos la base para tener la info en municipio-mes, listo para EDA y modelado."""

eda_cols=df.columns[:9]
print(eda_cols)

"""Del mapa oficial de categorías, podemos renombrar las intensidades de sequia:"""

eda_severidad = {np.nan: 0, 'D0': 1, 'D1': 2, 'D2': 3, 'D3': 4, 'D4': 5}
print(eda_severidad)

eda_sev_labels = {0: 'Sin sequía', 1: 'D0 Anormalmente seco', 2: 'D1 Sequía Moderada', 3: 'D2 Sequía Severa',
                  4: 'D3 Sequía Extrema', 5: 'D4 Sequía Excepcional'}
print(eda_sev_labels)

"""Transformamos las columnas de fecha en filas:"""

fecha_cols = [f for f in df.columns if f not in eda_cols]
print(fecha_cols)
print(f"{df.shape[0]} municipios, {len(fecha_cols)} columnas de fecha")

"""Considerando que tenemos informacion desde el mes de enero de 2003, hasta septiembre de 2026 que es hasta donde está actualizada la base, deberíamos tener 12 columnas por año de 2003 a 2025 y 9 columnas de 2026, i.e., 12×23+9=285, pero tenemos muchas más. Veamos porqué sucede esto."""

fechas_serie = pd.Series(fecha_cols)
print(fechas_serie)

"""Notemos que las fechas en un inicio son a final de mes, pero en las ultimas fechas tenemos dos fechas por mes, es decir, la información mostrada es quincenal, ya no mensual."""

conteo_anual = fechas_serie.dt.year.value_counts().sort_index()
print("Columnas de fecha por año: ")
print(conteo_anual)

"""---
Nuestra base cuenta con información de forma mensual en 2003-2013 (12 columnas/año) y de forma quincenal desde 2014 (~24 columnas/año). Para tener una base comparable en terminos de fechas, nos quedamos con la última lectura disponible de cada mes calendario (equivalente al cierre de mes que ya se usaba 2003-2013).
"""

# cols_mes = {}
# for c in fecha_cols:
#     key = (c.year, c.month)
#     if key not in cols_mes or c > cols_mes[key]:
#         cols_mes[key] = c
# cierrem_cols = sorted(cols_mes.values())
# print(f"{len(cierrem_cols)} periodos "
#       f"({cierrem_cols[0].date()} a {cierrem_cols[-1].date()})")

# df_eda = df[list(eda_cols) + list(cierrem_cols)].copy()
# print(df_eda.shape)
# print(df_eda.columns)

# dejamos las variables de eda_cols como vienen en el DataFrame, pero vamos a pivotear las columnas de fecha con su
# clasificación de sequia, es decir, las columnas de fecha ahora serán filas y se crea la columna de clasificacion_sequia
# para cada fecha y municipio
# el número de filas del nuevo DataFrame corresponde al número de periodos (285) por cada entidad federativa (32) para cada
# municipio dentro de ellas (depende de la entidad).
# df_clasif_municipio = df_eda.melt(id_vars=eda_cols, var_name='fecha', value_name='clasificacion_sequia')
# df_clasif_municipio['fecha'] = pd.to_datetime(df_clasif_municipio['fecha'])
# print(df_clasif_municipio)

# df_clasif_municipio['clasificacion_sequia'].unique()

# # número de registros en NaN, es decir, municipios sin sequía en un periodo.
# df_clasif_municipio['clasificacion_sequia'].isna().sum()

# # número de registros no vacíos, es decir con algun grado de sequía.
# len(df_clasif_municipio)-df_clasif_municipio['clasificacion_sequia'].isna().sum()

"""Mapeamos las intensidades para "eliminar" los nans, no es necesario imputarlos ya que por la naturaleza de la base los nan significa que no hay sequía."""

# df_clasif_municipio['intensidad'] = df_clasif_municipio['clasificacion_sequia'].map(eda_severidad)
# df_clasif_municipio['intensidad']

# df_clasif_municipio['intensidad_desc'] = df_clasif_municipio['intensidad'].map(eda_sev_labels)
# df_clasif_municipio['intensidad_desc']

# df_clasif_municipio['intensidad_desc'].unique()

# df_clasif_municipio['en_sequia'] = (df_clasif_municipio['intensidad'] >= 1).astype(int)
# df_clasif_municipio['en_sequia']

# df_clasif_municipio['en_sequia'].sum()

"""---

Dada la siguiente información en la fuente de donde obtuvimos nuestros datos:"*El archivo en Excel® contiene los municipios afectados por alguna condición desde anormalmente seco (D0) hasta sequía excepcional (D4). Para el periodo 2003 a 2015 se asignó la categoría de sequedad o sequía (D0 a D4) cuando la categoría cubría al menos el 40% de la superficie de dicho municipio. Sin embargo, debido a retroalimentación recibida, a partir de 2016 se asigna la categoría de sequía a la de mayor intensidad observada en algún municipio.*", y que nuestra base cuenta con información de forma mensual en 2003-2013 (12 columnas/año) y de forma quincenal desde 2014 ( al rededor de 24 columnas/año); se decidió que para tener una base comparable en terminos de fechas y de registro de información, **recortaremos la base a ene-2016** para contar con registros consistentes quincenales en cada mes.
"""

cols_2016 = [c for c in fecha_cols if c.year >= 2016]
print(f"Número de periodos a partir de 2016:", len(cols_2016))

df_eda = df[list(eda_cols) + list(cols_2016)].copy()
print(df_eda.shape)
print(df_eda.columns)

"""Dejamos las variables de `eda_cols` como vienen en el DataFrame, pero vamos a pivotear las columnas de fecha con su clasificación de sequía, es decir, las columnas de fecha ahora serán filas y se crea la columna de `clasificacion_sequia` para cada fecha y municipio. El número de filas del nuevo DataFrame corresponde al número de periodos (256) por cada entidad federativa (32) para cada municipio dentro de ellas (depende de la entidad)."""

df_clasif_municipio = df_eda.melt(id_vars=eda_cols, var_name='fecha', value_name='clasificacion_sequia')
df_clasif_municipio['fecha'] = pd.to_datetime(df_clasif_municipio['fecha'])
print(df_clasif_municipio)

# número de registros en NaN, es decir, municipios sin sequía en un periodo.
df_clasif_municipio['clasificacion_sequia'].isna().sum()

# número de registros no vacíos, es decir con algun grado de sequía.
len(df_clasif_municipio)-df_clasif_municipio['clasificacion_sequia'].isna().sum()

"""Mapeamos las intensidades para "eliminar" los nans, no es necesario imputarlos ya que por la naturaleza de la base los nan significan que no hay sequía."""

df_clasif_municipio['intensidad'] = df_clasif_municipio['clasificacion_sequia'].map(eda_severidad)
df_clasif_municipio['intensidad']

df_clasif_municipio['intensidad_desc'] = df_clasif_municipio['intensidad'].map(eda_sev_labels)
df_clasif_municipio['intensidad_desc']

df_clasif_municipio['en_sequia'] = (df_clasif_municipio['intensidad'] >= 1).astype(int)
df_clasif_municipio['en_sequia'].sum()

